### ISSUE TITLE
Feature request: export csv/Excel from a filter/search operation run against a Mosaic table? 

### ISSUE THREAD

**Issue by jaanli** [uwdata/mosaic#153]
**What would be the easiest way to implement export of a csv or Excel file from a Mosaic filter result against a WASM duckdb database in a parquet file?**

We have been using Mosaic to display hospital prices. 

For example these 106k prices at a large hospital in NYC: 

https://beta.payless.health/examples/mount-sinai.html (code: https://github.com/onefact/beta.payless.health/blob/main/docs/public/specs/yaml/mount-sinai.yaml; code to generate parquet file [here](https://colab.research.google.com/github/onefact/data_build_tool_payless.health/blob/main/notebooks/230809-mount-sinai.ipynb))

We've had several requests from journalists and policymakers who are not able to use python.

Specifically, they need to export a csv or use Excel to be able to make visualizations based off a query in Mosaic or a filtering result in a table. After this export, they usually use Excel or `R` (a very small number use python) to make visualizations before publishing a story.

For example, all of the prices related to C sections is a common query that a journalist or policymaker would want exported into a CSV:

<img width="500" alt="image" src="https://github.com/uwdata/mosaic/assets/5317244/1b2d0c3b-cf76-4461-8a69-8397a84aa13f">

(This demo is based off of the awesome Mosaic example here: https://github.com/uwdata/mosaic/blob/1590456b08bcb0bf4dd28ab8ac909b05a9ec0a69/docs/public/specs/yaml/athletes.yaml)

This potential feature would go a long way toward helping non-specialist users of Mosaic visualizations and dashboards analyze data further without the need to learn `duckdb`, python, etc.

This would enable data-driven journalism based off Mosaic filtering operations for a large number of newsrooms/journalists in our network @onefact who currently require training in Jupyter notebooks such as [this one](https://nbviewer.org/github/onefact/datathinking.org-codespace/blob/main/notebooks/princeton-university/week-1-visualizing-33-million-phone-calls-in-new-york-city.ipynb) before being able to tell stories.

**Comment by jheer** [comment]
You can most likely implement this directly yourself. If you want to create a CSV file stored on your local server:

1. Get the query for the (filtered) table you want
2. Use that query to issue a new query that writes a CSV file

For example:

```js
import { coordinator } from '@uwdata/vgplot';

// get query for Mosaic client, filtered according to any filterBy selection
const query = client.query(client.filterBy?.predicate(client));

// write CSV file for table to local server (will likely not work with WASM)
const csvQuery = `COPY (${query}) TO 'query.csv' WITH (HEADER 1, DELIMITER ',')`;
await coordinator().exec(csvQuery);
```

Note that I haven't tested the above. It might be possible to get something similar to work against DuckDB-WASM but you'd have to investigate what (if any) CSV export options DuckDB-WASM provides. Alternatively, you might instead use `coordinator().query(query)` and then convert the resulting Arrow table to whatever output format you want:

```js
import { coordinator } from '@uwdata/vgplot';

// get query for Mosaic client, filtered according to any filterBy selection
const query = client.query(client.filterBy?.predicate(client));

// get arrow table for query
const data = await coordinator().query(query);
// ...now use JS to convert arrow data to your desired output format

```

A different approach would be to get the current data table from a client, then map that to CSV yourself using JS methods. For example, most vgplot marks store their data as `client.data`. However, different clients may differ in how they do (or do not) expose their data and this may be subject to change over time, so this is not a reliable approach.

**Comment by jaanli** [comment]
Incredibly helpful -- thank you so much Jeff!! Will do 🙏
