### ISSUE TITLE
Feature request: confidence intervals for bar charts

### ISSUE THREAD

**Issue by jaanli** [uwdata/mosaic#163]
We have been using Mosaic for reporting on hundreds of thousands of hospital prices (demos here: https://beta.payless.health/examples/stlukes-bethlehem.html & https://beta.payless.health/examples/mount-sinai.html).

These prices are often listed according to minimum and maximum negotiated rates across several insurance products.

To accurately relay this information in a visualization, confidence intervals are necessary.

Would this be possible in Mosaic? 

(In the docs I only found confidence intervals mentioned for the `regressionY` mark here: https://uwdata.github.io/mosaic/vgplot/#connected-marks)

**Comment by jheer** [comment]
There are two pieces to this: 1. Compute a confidence interval, and 2. Draw the interval as a mark.

For part 1, there are many possibilities. You could compute a standard parametric CI via an expression (e.g., `MEAN(x) +/- 1.96 * STDDEV(x) / SQRT(COUNT())` for a 95% CI), though this bakes in a number of assumptions. Other methods, such as bootstraped CIs or model specific CIs would need to be computed through other means.

For part 2, given a calculated interval, you could use the `link` mark (for example) to visually represent the interval.

Something like this should work for a horizontally-oriented interval:

``` js
link(from(data), {
 x1: agg`AVG(x) - 1.96 * STDDEV(x) / SQRT(COUNT(*) FILTER (WHERE x IS NOT NULL))`,
 x2: agg`AVG(x) + 1.96 * STDDEV(x) / SQRT(COUNT(*) FILTER (WHERE x IS NOT NULL))`,
 y: 'your_y_variable'
})
```

**Comment by domoritz** [comment]
https://github.com/uwdata/mosaic/pull/380 adds support for variance.

**Comment by jheer** [comment]
Variance was always supported, but in the next release, variance, stddev, etc also have data cube indexing support. However, we don't yet support parsing of aggregate expressions to identify "indexable" aggregates, and so for now only top-level aggregate functions will be indexed. That said, if you have a client that queries directly for avg, stddev, and count as separate columns, they will be indexed and then you can put them together to form a client-side adjustable range of parametric CIs.

**Comment by jheer** [comment]
[Mosaic 0.9.0](https://github.com/uwdata/mosaic/releases/tag/v0.9.0) includes `errorbarX` and `errorbarY` marks in vgplot. The new [`athlete-height`](https://idl.uw.edu/mosaic/examples/athlete-height.html) example shows them in use.

This mark includes a transform to compute parametric confidence intervals in the database and the underlying queries are amenable to data cube indexes. The confidence level can be adjusted via a param without having to issue any new queries. For other kinds of intervals, you can instead compute those yourself and visualize them with standard ruleX/Y marks -- along with the `marker: "tick"` option if you want vertical edges on the interval.
