### ISSUE TITLE
Support web-standards platforms for the data server

### ISSUE THREAD

**Issue by tmcw** [uwdata/mosaic#174]
It'd be nice to be able to run the mosaic data server on Cloudflare Workers or Deno, and it seems kind of feasible from how it's set up currently - the only big change would be the native Node.js `duckdb` module, which would have to be swapped for the WASM port.

**Comment by domoritz** [comment]
We now have data servers in node, python, and rust. Writing another server or using wasm on the server should be easy enough. I'll close this issue for now since there wasn't any activity but we are open to PRs.
