### ISSUE TITLE
Enable the `castTimestampToDate` option for duckdb-wasm?

### ISSUE THREAD

**Issue by tmcw** [uwdata/mosaic#176]
When I try to use mosaic with duckdb-wasm using `vg.wasmConnector`, dates aren't treated as dates and my charts don't use date axes. It seems like DuckDB added an option to cast dates, but it's false by default:

- https://github.com/duckdb/duckdb-wasm/issues/393

But this doesn't look like it's toggled on for Mosaic, which causes time series data to be wonky when run directly in a browser.

**Comment by jheer** [comment]
Thanks for the suggestion! We are aware that there are some annoying type conversion issues (don't get me started on `BigInt`), some of which stem from the default conversions performed by the Arrow JS lib.

My main concern with this suggestion is that it could lead to inconsistent behavior across WASM and server deployments; we'd need to make sure the appropriate conversion is happening across this full surface area.

I haven't looked closely at the `castTimestampToDate` option, but I'd also want to make sure it isn't a pure cast that truncates timestamps to dates and thus loses information.

In the meantime, the WASM connector exposes the DuckDB instance, so custom configuration for your own use case should be viable.
