### ISSUE TITLE
Examples have hidden setup

### ISSUE THREAD

**Issue by tmcw** [uwdata/mosaic#177]
If I pull up the index example: https://uwdata.github.io/mosaic/examples/

I see code which looks complete, and to me suggests that if I have a file at `"data/stocks.parquet"`, then it should work if I paste it into an HTML file and do the proper importing of the library.

This doesn't work, though, because all of the examples have this init method:

https://github.com/uwdata/mosaic/blob/6a470c4b56946ad7e85fc02b463ea4eb7b8e6441/docs/.vitepress/theme/Example.vue#L10-L13

So right now if you copy an example, it'll give quite different behavior than what it has on the web - instead of working with a file, it'll try to connect to a coordinator server and fail. This seems like a stumbling block for folks trying to learn how to use this.

**Comment by jaanli** [comment]
I ran into this too for several hours (though am a noob at frontend development, so maybe it’s obvious! Though ChatGPT nor Claude could help me get the examples working in Next.js)

**Comment by jheer** [comment]
Thanks for pointing this out. We default to using the socket server connector, hence the need for this configuration step for purely web-based deployment. For better or worse there are multiple reasons we use the socket server by default: Mosaic provides the biggest delta against existing tools for really large datasets that also exceed what is reasonable to load in a browser, the WASM connector requires async initialization, and the WASM connector pulls in the full DuckDB-WASM dependency which some builds may prefer to tree-shake out.

One possible change, but one I'm not yet convinced of, would be to make the WASM connector the default connector.

In the meantime, it sounds like improved documentation might help. If you have ideas (or PRs!) please do feel free to share.
