### ISSUE TITLE
Need to refresh page to update Mosaic plot - non-deterministic behavior

### ISSUE THREAD

**Issue by jaanli** [uwdata/mosaic#186]
Not sure how to solve this bug, but Mosaic visualizations are needing to be refreshed after navigating to another page on the website. 

For example, clicking on https://www.payless.health/hospital/houston-methodist shows this:

![image](https://github.com/uwdata/mosaic/assets/5317244/5ffe286d-c944-4026-b347-5b51f0ed703e)

But then navigating to this page (https://www.payless.health/hospital/parkview-health) shows this: 

![image](https://github.com/uwdata/mosaic/assets/5317244/aedad262-23ba-4b18-9e18-ddd493d455f1)

And refreshing the page shows the actual Mosaic visualization: 

![image](https://github.com/uwdata/mosaic/assets/5317244/6c5d9a37-670f-40cc-a062-befc55659e75)

The Mosaic specs: 

https://github.com/onefact/payless.health/blob/main/docs/public/specs/yaml/houston-methodist-sorted-bars.yaml
https://github.com/onefact/payless.health/blob/main/docs/public/specs/yaml/parkview-health.yaml

From the console, it looks like the first click leads to a Binder error, but then when refreshing there are no errors - so I'm confused about how to replicate this bug:

Console log from the first click:
```
Error: Binder Error: Referenced column "name_minimum" not found in FROM clause!
Candidate bindings: "charges.payer"
LINE 1: SELECT DISTINCT "name_minimum" AS "value" FROM "charges...
                        ^
    runQuery https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.27.0/dist/duckdb-browser-eh.worker.js:11
    onMessage https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.27.0/dist/duckdb-browser-eh.worker.js:10
    onmessage https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.27.0/dist/duckdb-browser-eh.worker.js:24
[parse-spec.e96b9020.js:4:76051](https://www.payless.health/assets/chunks/parse-spec.e96b9020.js)
Error: Binder Error: Referenced column "min_charge" not found in FROM clause!
Candidate bindings: "source.payer"
LINE 1: SELECT "min_charge", "max_charge", "name_minim...
               ^
    runQuery https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.27.0/dist/duckdb-browser-eh.worker.js:11
    onMessage https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.27.0/dist/duckdb-browser-eh.worker.js:10
    onmessage https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.27.0/dist/duckdb-browser-eh.worker.js:24
[parse-spec.e96b9020.js:4:76051](https://www.payless.health/assets/chunks/parse-spec.e96b9020.js)
Error: Binder Error: Referenced column "min_charge" not found in FROM clause!
Candidate bindings: "source.payer"
    runQuery https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.27.0/dist/duckdb-browser-eh.worker.js:11
    onMessage https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.27.0/dist/duckdb-browser-eh.worker.js:10
    onmessage https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.27.0/dist/duckdb-browser-eh.worker.js:24
```

Open to advice, thank you!!

**Comment by jheer** [comment]
I believe the issue stems from the fact that your specs create a table with the same name. By default, the data loaders will not replace an existing table, so when you navigate from one page to another without reloading, the DuckDB-WASM instance persists, including any previously loaded tables. This would explain both the binder error and why re-loading resolves the issue.

So I think there are multiple solutions you could apply...

1. If you want to replace any existing table with the same name, update your data definition to specify this:

```yaml
data:
  charges: { file: data/EIN_74110155_houston-methodist-hospital.parquet, replace: true }
```

2. Or, if you always use distinct table names, your app will load all the various tables and keep them loaded (until the page is reloaded).

3. Alternatively, you could update your web application logic to first drop all tables when navigating to a new page, basically performing a "hard reset" of the DuckDB-WASM instance.

For simplicity (and to prevent the number of loaded data tables from getting too large), I would probably default to option 1 above -- assuming this does not interfere with other Mosaic specs loaded on the same page.

**Comment by jaanli** [comment]
Got it, thank you so much @jheer! That makes sense, will give it a shot 🙏
