### ISSUE TITLE
Data is cached even after table is replaced unless `.configure` is called 

### ISSUE THREAD

**Issue by mhkeller** [uwdata/mosaic#232]
I made a full reproduction repo: https://github.com/mhkeller/mosaic-cache-bug

I noticed that if I reuse a table name when creating a table from a parquet file using `CREATE OR REPLACE`, the data is not replaced.

I thought the issue was due to Mosaic cacheing the results so I set the following, which fixes the issue:

```js
await vg.coordinator().configure({
  cache: false
})
```

However, it doesn't matter what the value of `cache` here is. The bug is fixed as long as this configure call is made. For example, setting it to [the defaults](https://github.com/uwdata/mosaic/blob/a3b78fef28fcc3e711bb922c97c3113aa6cf9122/docs/api/core/coordinator.md?plain=1#L43) fixes it:

```js
await vg.coordinator().configure({
  cache: true,
  index: true
})
```

This also fixes it:

```js
await vg.coordinator().configure({})
```

## Expected

https://github.com/uwdata/mosaic/assets/498744/c0aee7bd-ef5f-455f-a987-9b84cf4f9acb

## Actual

https://github.com/uwdata/mosaic/assets/498744/9cc677be-a4a3-4474-95da-136e2f1b6e0b

**Comment by jheer** [comment]
Thanks for the issue! Mosaic runs "on top" of a DuckDB instance but does not get notifications from the database if/when underlying tables change (even if the change occurs via queries issued through Mosaic itself). This is a known limitation of our research prototype. So unfortunately you will have to "manually" flush the cache upon underlying table changes. The preferred way of doing this is:

```js
coordinator().clear({ clients: false, cache: true })
```

If that is not working, please file an issue specific to that!

**Comment by mhkeller** [comment]
Got it – thanks for the quick reply!
