### ISSUE TITLE
Connecting to our own duckdb-wasm

### ISSUE THREAD

**Issue by maelp** [uwdata/mosaic#277]
In my app, I'm already using duckdb-wasm to let the user do queries.

I see that when using the `wasmConnector` in mosaic, it creates its own duckdb database, that is then fed data.

Would there be a way to allow it to use my database instead?

and would there be a way to feed the data efficiently from my duckdb-wasm instance to Mosaic efficiently, so that after a user does a request using my code, it can "feed" the result to Mosaic to plot it efficiently?

Or should I instead "scrap" my duckdb-wasm instance and use the one from Mosaic directly? won't there be interferences if I do this?

**Comment by maelp** [comment]
My use-case would be something like a kind of "Jupyter" notebook (but manually done), where the user can do queries and examine results from my duckdb-wasm instance (I print out the result), then it would click on a visualization widget, which would feed the data to Mosaic. I'm not sure what would be the most convenient way to implement this?

It seems a bit "backward" that if Mosaic is a kind of "feature on top" of my already existing query page, I would still use its database directly no?

**Comment by jheer** [comment]
It should be relatively easy to modify the wasm connector to accept an existing duckdb-wasm instance and use that instead of instantiating a new instance. I'll put this on our short term roadmap. PRs also welcome in the interim.

**Comment by maelp** [comment]
Thanks! For now I'll do a workaround where I create the equivalent of wasmConnector using my own db

**Comment by jheer** [comment]
I updated the WASM connector in https://github.com/uwdata/mosaic/issues/277, to be included in the next release.

**Comment by maelp** [comment]
Nice thanks! At what interval are new releases deployed?
