### ISSUE TITLE
API not clear

### ISSUE THREAD

**Issue by maelp** [uwdata/mosaic#281]
Am I right in understanding that when I want to do a "complex query" on my DuckDb database I should do something like this

```
  await vg.coordinator().exec(`
CREATE OR REPLACE VIEW DataView AS
SELECT timestamp, value.temperature_front AS y
FROM recent_cse(${numWeeks})
WHERE bms_id = '${bms_id}';
`);
  mosaicPlotContainer.value.replaceChildren(
    vg.plot(
      vg.line(vg.from("DataView"), { x: "timestamp", y: "y" }),
    )
  );

```

rather than what I would have expected by reading the view (the "from" method is not very documented)

```
  mosaicPlotContainer.value.replaceChildren(
    vg.plot(
      vg.line(vg.from("recent_cse(4)").select({timestamp: "timestamp", y: "value.temperature_front"}).where(vg.eq("bms_id", bmsId)), { x: "timestamp", y: "y" }),
    )
  );

```

**Comment by maelp** [comment]
Although when I run the above query, it takes a LONG time (I stopped it) so I guess something is not working (eg it's not doing the filtering properly)

**Comment by jheer** [comment]
The typical setup is to either load/access existing tables directly OR issue a complex query once as part of your data prep, then use `vg.from(tableOrViewName)` to access the results. In the future it is possible we could support "inline" queries for the mark data, but we don't currently and its not on our roadmap. Instead, marks construct their own query with select and potentially group by, aggregates, and/or filtering based on the mark options and filterBy selection.

In any case, having custom queries for each mark runs against the grain of how Mosaic supports and optimizes filtering via the `Selection` abstraction, which is optimized for filtering against a shared table/view.

**Comment by maelp** [comment]
So more precisely, if I do this it's "relatively fast", doing 40 HEAD queries and 119 GET queries to my S3 parquet files

```
const bms_id = "sFfuW3GC3lELeWmLe4Yl";
  const numWeeks = 4;
  await vg.coordinator().exec(`
CREATE OR REPLACE VIEW DataView AS
SELECT bms_id, timestamp, value.temperature_front AS y
FROM recent_cse(${numWeeks})
WHERE bms_id = '${bms_id}';
`);
  // IF I ADD THE FOLLOWING LINE IT IS MUCH FASTER
  await vg.coordinator().query(`SELECT * from DataView`);
  mosaicPlotContainer.value.replaceChildren(
    vg.plot(vg.line(vg.from("DataView"), { x: "timestamp", y: "y" }))
  );
```

<img width="368" alt="image" src="https://github.com/uwdata/mosaic/assets/15458/5147de86-1318-4d7f-88a7-8d78b1f69d7d">

but if I remove it, it is quite slow

```
const bms_id = "sFfuW3GC3lELeWmLe4Yl";
  const numWeeks = 4;
  await vg.coordinator().exec(`
CREATE OR REPLACE VIEW DataView AS
SELECT bms_id, timestamp, value.temperature_front AS y
FROM recent_cse(${numWeeks})
WHERE bms_id = '${bms_id}';
`);
  // I REMOVED THE "PRELOADING QUERY"
  mosaicPlotContainer.value.replaceChildren(
    vg.plot(vg.line(vg.from("DataView"), { x: "timestamp", y: "y" }))
  );
```

now it does 15 HEAD and 316 GET queries to get EXACTLY THE SAME RESULTING graph... taking much longer

<img width="331" alt="image" src="https://github.com/uwdata/mosaic/assets/15458/0e1aa876-c891-4ff4-ae28-11623662babf">


any idea what I'm doing wrong? or is there a bug?

**Comment by maelp** [comment]
@jheer okay thanks for the answer (you might be interested in the fact that doing a "pre-fetch query" is much faster, although I have no idea why, happy to give more details if you want)

perhaps this should be detailed in the doc, as this was not clear to me (in particular seing the "vg.from()" I imagined it was the same as "vg.Query.from"

**Comment by maelp** [comment]
(you might want to reopen this issue with "bug" as there seems to be something going on when there is no query "pre-fetching")
