### ISSUE TITLE
Slow query when not prefetching data

### ISSUE THREAD

**Issue by maelp** [uwdata/mosaic#282]
I'm adding back the comment at https://github.com/uwdata/mosaic/issues/281#issuecomment-1919478524

So more precisely, if I do this it's "relatively fast", doing 15 HEAD queries and 119 GET queries to my S3 parquet files

```
const bms_id = "sFfuW3GC3lELeWmLe4Yl";
  const numWeeks = 4;
  await vg.coordinator().exec(`
CREATE OR REPLACE VIEW DataView AS
SELECT bms_id, timestamp, value.temperature_front AS y
FROM recent_cse(${numWeeks})
WHERE bms_id = '${bms_id}';
`);
  // IF I ADD THE FOLLOWING LINE IT IS MUCH FASTER
  await vg.coordinator().query(`SELECT * from DataView`);
  mosaicPlotContainer.value.replaceChildren(
    vg.plot(vg.line(vg.from("DataView"), { x: "timestamp", y: "y" }))
  );
```

<img width="326" alt="image" src="https://github.com/uwdata/mosaic/assets/15458/9f0810b8-c1cc-4a6c-beb6-b59c4e5e0fbe">

but if I remove it, it is quite slow

```
const bms_id = "sFfuW3GC3lELeWmLe4Yl";
  const numWeeks = 4;
  await vg.coordinator().exec(`
CREATE OR REPLACE VIEW DataView AS
SELECT bms_id, timestamp, value.temperature_front AS y
FROM recent_cse(${numWeeks})
WHERE bms_id = '${bms_id}';
`);
  // I REMOVED THE "PRELOADING QUERY"
  mosaicPlotContainer.value.replaceChildren(
    vg.plot(vg.line(vg.from("DataView"), { x: "timestamp", y: "y" }))
  );
```

now it does 15 HEAD and 316 GET queries to get EXACTLY THE SAME RESULTING graph... taking much longer

<img width="331" alt="image" src="https://github.com/uwdata/mosaic/assets/15458/0e1aa876-c891-4ff4-ae28-11623662babf">

any idea what I'm doing wrong? or is there a bug?

**Comment by jheer** [comment]
Whatever is happening here is likely due to DuckDB, not Mosaic. You can log the queries coming out of Mosaic (e.g., use DuckDB-WASM with logging enabled) and see if you get similar performance results when simply issuing queries directly. I'd recommend starting with that to better isolate the issue.

**Comment by maelp** [comment]
I have logging in duckdb-wasm (using ConsoleLogger), is that what you mean? I don't see any query printed though...

**Comment by maelp** [comment]
so when adding the prefetch query

my view creation
<img width="502" alt="image" src="https://github.com/uwdata/mosaic/assets/15458/228dcafa-569e-4e60-b3ff-fe5bfb8a38a9">
then the select for the plot
<img width="498" alt="image" src="https://github.com/uwdata/mosaic/assets/15458/3c86535e-e795-45c3-8caa-39683a51d01b">
then a describe
<img width="490" alt="image" src="https://github.com/uwdata/mosaic/assets/15458/a7c5ae64-92c8-4bf7-bd21-4eb777582d9c">
then a count
<img width="491" alt="image" src="https://github.com/uwdata/mosaic/assets/15458/25024e87-cb8b-4bc9-b4f5-9ea939a079d0">
then a min / argmin
<img width="506" alt="image" src="https://github.com/uwdata/mosaic/assets/15458/6e763c93-5778-4323-96f4-ea002b081c29">

**Comment by maelp** [comment]
If I remove my prefetch "SELECT * from DataView" this is what happens:

<img width="474" alt="image" src="https://github.com/uwdata/mosaic/assets/15458/189d1b93-71cf-41dc-bd3b-0c0a56b3967f">

then NO PREFETCH

then describe

<img width="312" alt="image" src="https://github.com/uwdata/mosaic/assets/15458/4eda0ba4-0f0b-4885-a741-be1a6e183f1e">


then count (this seems to take a very long time and require more data than when prefetching)

<img width="489" alt="image" src="https://github.com/uwdata/mosaic/assets/15458/2b948b16-abaf-4278-a4ea-37d52fcf66b3">

then select min

<img width="498" alt="image" src="https://github.com/uwdata/mosaic/assets/15458/337ec90d-5dfc-43af-9a88-c4d6e9aedaba">

**Comment by jheer** [comment]
Looks like this is a DuckDB internal issue. Creating a view may result in multiple network calls, it's possible the "prefetch" query results in some internal cache (materialized view) being constructed, but its hard to say.

If your data is small enough to simply copy over the network, creating a table (or temporary table) seems like a better way to go. And if its not, DuckDB-WASM may not be the best option, a DuckDB server or using MotherDuck should scale better.
