### ISSUE TITLE
Release mosaic-widget on duckdb==0.10.0 dependency

### ISSUE THREAD

**Issue by frtennis1** [uwdata/mosaic#295]
Hello! Small request hopefully: would it be possible to release the new version of the `mosaic-widget` package? 

When I try to `pip install duckdb-server`, it gives me some grief because it depends on `duckdb==0.10.0`, but I also have installed `mosaic-widget==0.3.3` which depends on an older duckdb (but I noticed that the new version of `mosaic-widget` on main already has a `duckdb==0.10.0` dependence so I think this would be fixed with a new release and my upgrading to it)

**Comment by domoritz** [comment]
Happy to make a release. @jheer any objections?

**Comment by jheer** [comment]
Please do @domoritz!

**Comment by domoritz** [comment]
https://pypi.org/project/mosaic-widget/0.5.0/ is out.
