### ISSUE TITLE
Documentation request: how to create a custom client

### ISSUE THREAD

**Issue by RyanChapman2x** [uwdata/mosaic#303]
I've created a custom client by following the guidelines in the current documentation. However, the coordinator refuses to call MosaicClient.query(). And if I put my interactor into a plot, then the plot errors as soon as it hits this unexpected "directive". I tried coercing my class using the method in input.js like you did with the slider interactor, but I still run into problems. I can sometimes get coordinator to call .query() but it will neither actually query the database nor return a result to .queryResult(), so no action ever gets taken.

I also see a vague reference to coordinator "registration" in the docs, but there's no actual info on what it means to register a client with the coordinator:

> Upon registration, the coordinator calls the client fields() method to request a list of fields...

What, exactly, is the expected way to "register" or incorporate a custom client into a project?

**Comment by RyanChapman2x** [comment]
`coordinator.connect(client)`

There it is.

**Comment by jheer** [comment]
Yep, that's it. Thanks for the feedback. I'll update the documentation to make it clearer how to register a client with a coordinator.
