### ISSUE TITLE
mosaic jupyter widget example typo?

### ISSUE THREAD

**Issue by mjohnson11** [uwdata/mosaic#314]
Hi y'all, just checking this out for the first time. I could be missing something but I think the variable `mosaic` on the last two lines of the bottom code block [here](https://uwdata.github.io/mosaic/jupyter/) should be `widget`? In any case `mosaic` isn't defined in the example code. If this isn't the right place for documentation comments let me know!

**Comment by jheer** [comment]
Thanks for flagging this!

@domoritz can you take a look?
