### ISSUE TITLE
Feature: Support for a Tip mark / Tooltip support

### ISSUE THREAD

**Issue by Unemyr** [uwdata/mosaic#315]
First of all, thanks for a terrific project and a lot of great work done so far!

Would be really useful to have a generic Tip mark available (referencing the existing one in Observable: https://observablehq.com/plot/marks/tip). I saw that the Dot mark has a tip: [true/false] variable enabled but it does not seem to be supported in the other mark types? Either of these 2 approaches probably works fine.

Best regards,

Erik

**Comment by jheer** [comment]
Indeed, right now we don't expose the tip mark. Most (but not all) vgplot marks support `tip: true`. Note that you can also provide object-valued `tip` settings to further customize the tooltips; see the [Observable Plot documentation](https://observablehq.com/plot/features/marks#mark-options) for more.

Marks that do _not_ currently support tooltips include raster-based marks (`raster`, `heatmap`, and `denseLine`) and the `geo` mark (though you can generate centroid `dot` marks and add tips to those, [as done here](https://uwdata.github.io/mosaic/examples/us-state-map.html)). Note that Observable Plot also shares these limitations at the moment.
