### ISSUE TITLE
Heatmap not working 

### ISSUE THREAD

**Issue by DougRzz** [uwdata/mosaic#319]
The heatmap examples are not working in jupyter. I believe it is because heatmap.js is missing from the marks folder.

BTW. Thanks for this great library. I'm looking forward to trying this out on some large time series datasets.

**Comment by jheer** [comment]
The `heatmap` mark is defined in the same file as the `raster` mark, as it is just a raster with different default options.

Rather, it looks like the Python widget version is behind the JS lib. We need to publish the latest version to pypi. @domoritz has been performing the Python releases, but we should really consolidate here!

@domoritz can we modify the release process (`npm run release`) to include the python libs?

**Comment by domoritz** [comment]
I released new package versions and also sent a [pull request](https://github.com/uwdata/mosaic/pull/322) to include the python package releases in `rpm publish`.
