### ISSUE TITLE
PanZoom not working with RasterMark

### ISSUE THREAD

**Issue by jonrmayer** [uwdata/mosaic#345]
Very simple example - I did try all types of configuration - but the following would not work:
hconcat: 
  - vconcat:
    - plot:
      - mark: frame
      - { mark: raster, data: { from: summary_data}, x: px,y: py, fill: density  } 
      - { select: panZoom }

**Comment by jonrmayer** [comment]
Apologies, I should have mentioned that the x and y scales were changing but the raster image itself remained static.

**Comment by jheer** [comment]
Thanks for the issue! Right now you can zoom a raster display via overview + detail interactions (as in the Line Density chart example), but the PanZoom interactor is not well supported (sorry!). I'll flag this as both a documentation and enhancement issue for now.

**Comment by jonrmayer** [comment]
Thank you!. I am a geospatial data guy - hence the obsession with panning & zooming ;-)  This is a great little library with a lot of current/future potential and I am putting together an demo for internal consumption. Hopefully, this will encourage some of my colleagues ( senior JS developers ) to get involved. This might take some time. Thanks again for your research and work on this project.

**Comment by jheer** [comment]
Actually, upon additional inspection I discovered a bug. Your spec _should_ work (though the performance of raster pan/zoom will depend on the data set size, raster size, and database performance - and so range from very smooth to very chunky. I've update this issue to reflect the bug and will try to get a fix in place soon.

**Comment by jheer** [comment]
Fixed by [d3e521a](https://github.com/uwdata/mosaic/commit/d3e521a69876732609a8119959b8078392dd5859).
