### ISSUE TITLE
table bugs on crossfilter interactions after scrolling

### ISSUE THREAD

**Issue by declann** [uwdata/mosaic#363]
Hi,

I include a table in a linked interaction, here for convenience:

https://observablehq.com/@declann/linked-visuals-for-data-exploration-mosaic-duckdb

Scrolling the table seems to cause bugs on follow up interactions.

Steps to reproduce:

- select any one dot (or a handful) in the scatter to verify that table works: 
![image](https://github.com/uwdata/mosaic/assets/353214/f512cb70-d250-48a2-bc0e-7115bb2716bb)
- unselect it so the table resets to a large list
- scroll down in the table until more data is dynamically added
- now select any one dot again: the table is empty rather than showing the corresponding data
![image](https://github.com/uwdata/mosaic/assets/353214/23bbc669-3d82-4c33-8659-c81ea210ce91)

The table will react to large filters at this point (not sure if correctly, & most other filters are large hence why better to try with one dot), but it doesn't seem to fix more granular selections like this.

ps was really nice to produce this with the architecture and visualization apis, great work! (neat examples helped a tonne!)

Thanks
Declan

**Comment by jheer** [comment]
Thanks for sharing the issue and the easy-to-check replication! Fixed by #434.
