### ISSUE TITLE
Parallel Queries

### ISSUE THREAD

**Issue by domoritz** [uwdata/mosaic#388]
Right now, Mosaic sends one query after another to the server. This means that it always has to wait for a result to return before a next query is sent which means the server is not used effectively. As a first step, try to send a batch of queries. By batching we still maintain the order or queries which avoids potential bugs with out-of-order responses. In the next step, try building a HTTP server that processes requests in parallel and returns results out of order without leading to bugs in the UI.

**Comment by kzhang31415** [comment]
working on this issue
