### ISSUE TITLE
Can’t specify multiple inputs’ values for the same selection

### ISSUE THREAD

**Issue by tarekrached** [uwdata/mosaic#401]
I'm unable to specify multiple inputs’ values for the same selection.

Repro: Add `value: fencing` and `value: female` to the first two menus ([here](https://github.com/uwdata/mosaic/blob/67eb20c905565071d21bf6e451070d9270d8ae8e/specs/yaml/athletes.yaml#L15) and [here](https://github.com/uwdata/mosaic/blob/67eb20c905565071d21bf6e451070d9270d8ae8e/specs/yaml/athletes.yaml#L20)) in `specs/yaml/athletes.yaml`  and load the “Athletes” example in the dev server. See that only the first menu has its value pre-selected:

<img width="582" alt="image" src="https://github.com/uwdata/mosaic/assets/167218/2212ab58-864b-4537-b8b0-99c3882dbf8d">

**Comment by jheer** [comment]
Thanks! I suspect the shared selection is updating with the first value and that this is then interfering with the second value being properly added. Such values *should* interfere when the selection resolution strategy is `single`, but not in this case where we have a standard `intersect` selection. I'll look into it.

**Comment by jheer** [comment]
PR #403 fixes this issue: initial values should be properly reflected in the menu and populated in the selection. It will be included in the next release.

However, note that setting initial values can lead to other wrinkles if you are using `Fixed` domains. Fixed domains initialize to the first data seen and are then locked in place. So if you start with filtered data, you will get locked-in domains over the filtered ranges. So for now you may want to "hardwire" scale domains to desired values to have the scales reflect the full range of the data _and_ remain fixed.
