### ISSUE TITLE
Support automatic time binning

### ISSUE THREAD

**Issue by domoritz** [uwdata/mosaic#427]
It would vibe great if Mosaic had a way to bin time fields by time units (month, day etc) similar to https://vega.github.io/vega-lite/docs/timeunit.html and bin automatically by the most appropriate time unit. 

Previous discussion at https://github.com/uwdata/mosaic/issues/283#issuecomment-1930662494

**Comment by domoritz** [comment]
@hamilton wrote a blog post about a query to determine the smallest time unit used in some data which could be useful for heuristics here as well: https://www.hamiltonulmer.com/smallest-timegrain-heuristic/.

**Comment by jheer** [comment]
Mosaic does support time binning. First, one can directly use existing [DuckDB date part methods](https://duckdb.org/docs/sql/functions/datepart#part-functions) like `quarter`, `month`, `dayofweek`, etc. To bin a date without changing the type (resulting in a JS `Date` object in the browser), `mosaic-sql` includes the methods [`dateMonth`, `dateMonthDay`, and `dateDay`](https://uwdata.github.io/mosaic/api/sql/date-functions.html). I agree that a method for automatically determining a "nice" binning unit could be helpful!

p.s. FWIW the `bin` transform supports temporal values as well, but treats them as numbers, currently without consideration for nice units.

**Comment by derekperkins** [comment]
Not sure if this would fall under Mosaic or DuckDB, but it would also be nice to handle day of week alignment when binning, for MoM and YoY
