### ISSUE TITLE
`duckdb-server` not working in docker container.

### ISSUE THREAD

**Issue by bbollen23** [uwdata/mosaic#454]
Apologies in advance if this is not the best place to post this, but I cannot find a solution to this problem anywhere. We'd like to deploy the duckdb-server as a separate container in a docker compose file so that we can use Mosaic in our Vue application.

Here is the Dockerfile I created:

```
FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir duckdb-server

EXPOSE 3000

CMD ["duckdb-server"]
```

This dockerfile builds successfully but running it gives the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/duckdb-server", line 5, in <module>
    from pkg.__main__ import serve
  File "/usr/local/lib/python3.11/site-packages/pkg/__main__.py", line 7, in <module>
    from pkg.server import server
  File "/usr/local/lib/python3.11/site-packages/pkg/server.py", line 8, in <module>
    from socketify import App, CompressOptions, OpCode
  File "/usr/local/lib/python3.11/site-packages/socketify/__init__.py", line 5, in <module>
    from .socketify import (
  File "/usr/local/lib/python3.11/site-packages/socketify/socketify.py", line 12, in <module>
    from .native import ffi, lib
  File "/usr/local/lib/python3.11/site-packages/socketify/native.py", line 409, in <module>
    lib = ffi.dlopen(library_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '/usr/local/lib/python3.11/site-packages/socketify/libsocketify_linux_amd64.so': /usr/local/lib/python3.11/site-packages/socketify/libsocketify_linux_amd64.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/usr/local/lib/python3.11/site-packages/socketify/libsocketify_linux_amd64.so'
```

I have ensured that within my docker container, the path `/usr/local/lib/python3.11/site-packages/socketify/libsocketify_linux_amd64.so` does exist. Furthermore, I'm able to ping that directory (using `RUN ls -l /usr/local/lib/python3.11/site-packages/socketify/libsocketify_linux_amd64.so`) during the build process, which also completes successfully. I've also tried using "pipx" in my docker container rather than pip which resulted in the same error.

I've scoured everything and cannot find a solution to this issue at all. Not sure if I'm just thinking about this incorrectly, but any help would be appreciated. I was able to run `duckdb-server` locally very easily.

**Comment by domoritz** [comment]
I'd suggest raising this with socketify as it's not really mosaic related. 

In the meantime, you can use the node server or soon the rust server I have in a pull request.

**Comment by bbollen23** [comment]
> I'd suggest raising this with socketify as it's not really mosaic related.
> 
> In the meantime, you can use the node server or soon the rust server I have in a pull request.

Thanks! Appreciate the feedback.

**Comment by domoritz** [comment]
I'd also suggest not using a slim version since that probably doesn't have some dependencies that you may need.

**Comment by bbollen23** [comment]
Got it, thanks! Got this up and running which is great.

**Comment by domoritz** [comment]
What was the solution you found?

**Comment by bbollen23** [comment]
The solution was just using the node server instead. I just made a small Node server based on the example in the documentation and it worked out great.
