### ISSUE TITLE
loadJSON should no longer pass `json_format`

### ISSUE THREAD

**Issue by geoffreyd** [uwdata/mosaic#455]
As seen in [this update to duckdb](https://github.com/duckdb/duckdb/pull/7478), `json_format` has been changed to `format`, and also doesn't need to be passed by at all by default.

The use of `json_format` is causing this error: 

```
Error: Binder Error: Invalid named parameter "json_format" for function read_json
```
when calling `vg.loadJSON('dashboard', 'rows.json')`.

I'm using `wasmConnector`.

**Comment by domoritz** [comment]
Good catch. Want to send a pull request?

**Comment by geoffreyd** [comment]
I needed to create a json file to add an appropriate test, hopefully this is OK.
