### ISSUE TITLE
Race conditions and hanging in 0.10.0

### ISSUE THREAD

**Issue by andyrooger** [uwdata/mosaic#458]
I'm using mosaic core and sql directly to interact with non-mosaic charting libraries. It's great work and pretty solid in general. However I've noticed once there are enough clients and enough data to slow things down slightly I regularly, but not consistently, get the following issues if I interact too quickly with the clients.

1. I get errors like `Error: Catalog Error: Table with name cube_index_6356947a does not exist! Did you mean "cube_index_6ed6ff70"?` from queries
2. Some clients stop receiving data completely. Debugging shows some requests are queued but never executed, and some requests are executed but the data is never emitted.

Causes seem to be as follows (I'm using a crossfiltered selection if that matters)

### Missing Indexes

1. A filter is changed, triggering updates to the other clients using the `DataCubeIndexer`
2. Requests are queued for generating indexes, requests are generated for fetching the data using the indexes.
3. Another client calls `requestQuery` which in turn calls `dataCubeIndexer.clear()` and cancels the requests for index creation (if they haven't had chance to run yet). It does not cancel the requests that use the indexes (which is presumably correct since we still want that data - a request from elsewhere hasn't changed that)
4. Requests run, index is missing, bang.

**I'm addressing this locally by disabling the index request cancellation, but I don't know if that's something you'd want to do generally.**

### Hung Updates
1. When requests are cancelled (not cleared) in the `QueryManager` they seem to be dequeued but never settled.
    - Throttled methods waiting on a request such as `MosaicClient.requestUpdate()` will hang indefinitely and block all future calls
    - `AsyncDispatch` seems hit the same problem in `emit` since `updateSelection` from `Coordinator` can awaits requests
2. In addition when using `throttle`, if a promise from a throttled callback is rejected, the throttle ends up hung - never clearing the current callback promise

**This seems straightforward to address - I'm happy to provide a PR.**

Thanks!

**Comment by andyrooger** [comment]
If it helps anyone, I'm using the following monkey patches locally for now

```js
import { Coordinator, MosaicClient } from '@uwdata/mosaic-core';

// --- throttle hang on callback rejection ---
// Can't patch throttle, but the usage I primarily care about is in MosaicClient._requestUpdate - Just make sure it never fails

const requestQueryFn = MosaicClient.prototype.requestQuery;
MosaicClient.prototype.requestQuery = async function (...args) {
    try {
        await requestQueryFn.apply(this, args);
    }
    catch {
        /* ignore */
    }
};

// --- cancelled requests never complete ---
const QueryManager = new Coordinator().manager.constructor;
QueryManager.prototype.cancel = function cancel(requests) {
    const set = new Set(requests);
    if (set.size) {
        this.queue.remove(({ result }) => {
            if (set.has(result)) {
                result.reject('Cancelled');
                return true;
            }
            return false;
        });
    }
};

// --- missing indexes ---
const DataCubeIndexer = new Coordinator().dataCubeIndexer.constructor;
DataCubeIndexer.prototype.clear = function cancel() {
    this.indexes.clear();
    this.active = null;
};
```

**Comment by jheer** [comment]
Thanks for this! The changes look good overall. If you’re up for opening a PR, I’d be happy to review.
