### ISSUE TITLE
Website examples do not work since recent updates

### ISSUE THREAD

**Issue by domoritz** [uwdata/mosaic#464]
It looks like the recent updates broke some examples with dates. This is at https://idl.uw.edu/mosaic/what-is-mosaic/. 

<img width="1098" alt="Screenshot 2024-07-18 at 10 18 29" src="https://github.com/user-attachments/assets/d35d170e-85c4-4ef3-b1e6-0b385d974a7f">

**Comment by domoritz** [comment]
Seems like I can repro the issue in the duckdb cli

```
create table stocks as  from 'data/stocks.parquet';
D CREATE TEMP TABLE IF NOT EXISTS labels AS SELECT MAX(Date) as Date, ARGMAX(Close, Date) AS Close, Symbol FROM stocks GROUP BY Symbol;
D SELECT "Date", Close / (SELECT MAX(Close) FROM stocks WHERE Symbol = source.Symbol AND Date = 1525996800000) AS "y", "Symbol" FROM "labels" AS "source";
Conversion Error: Unimplemented type for cast (BIGINT -> DATE)
LINE 1: ...HERE Symbol = source.Symbol AND Date = 1525996800000) AS "y", "Symbol" FROM "l...
```

**Comment by jheer** [comment]
I suspect this stems from `Date` values being mapped by Arrow to JS numbers instead of JS `Date`s (this is a change in behavior I noticed recently updating Arquero). However, when I build the Mosaic website locally I'm not seeing any errors, so I need to dig more to see if I can recreate and pinpoint the issue.

**Comment by domoritz** [comment]
The error happens when you hover.  I see it locally. I think the problem is that the nearest interactor returns a number rather than a date which would be mapped through epoch_ms.

**Comment by jheer** [comment]
I cleared dependencies and recreated it locally. It is indeed a change in Arrow behavior. I added an explicit coercion to JS dates when extracting Date values from Arrow and pushed the change. The site appears to be fixed.

**Comment by domoritz** [comment]
I can confirm that this fixes it.
