### ISSUE TITLE
ruleX from Selection does not work with timestamps (but does with numerics, and with a Param)

### ISSUE THREAD

**Issue by frtennis1** [uwdata/mosaic#502]
The following snippet does not display a vertical rule on mouseover when you set the `"x": "ts"` (a timestamp) but does when you set `"x": "x_val"` (a numeric),

```
x = np.linspace(0,10, num=50)
df = pd.DataFrame({
    "x_val": x, 
    "y_val": np.sin(x), 
    'ts': pd.date_range('2023-05-25 09:30', freq='1min', periods=50)
})

spec = {
    "plot": [
        {
            "mark": "lineY",
            "data": {"from": "df"},
            "x": "ts",
            "y": "y_val",
            'marker': True,
        },
        {"select": "nearestX", "as": "$myXValue"},
        {"mark": "ruleX", "x": "$myXValue"},
    ],
}
MosaicWidget(spec, data={'df': df})
```

**Doesn't work**
<img width="709" alt="image" src="https://github.com/user-attachments/assets/590cd36f-06af-438f-ab07-c69442537fe6">

** Does work**

<img width="688" alt="image" src="https://github.com/user-attachments/assets/f18f7dc9-c959-4035-afcd-d9750cc8b143">

Extra curious is that it starts working again for a timestamp if you make `$myXValue` a regular parameter (instead of a Selection), snippet that works:

```
spec = {
    "plot": [
        {
            "mark": "lineY",
            "data": {"from": "df"},
            "x": "ts",
            "y": "y_val",
            'marker': True,
        },
        {"select": "nearestX", "as": "$myXValue"},
        {"mark": "ruleX", "x": "$myXValue"},
    ],
    'params': {'myXValue': {'date': '2023-05-25 09:30'}},
}
MosaicWidget(spec, data={'df': df})
```

<img width="710" alt="image" src="https://github.com/user-attachments/assets/d70ecc7d-aaf0-4cfb-a44c-e83c16d831a1">

**Comment by jheer** [comment]
Thanks for catching this. In general, selections may not work as they may involve more complicated criteria with multiple values. However, in this case, there is only a single value and so it should be able to work. I updated the clause generation logic of the `nearest` interactor to recognize this single-field case and generate a compatible selection clause in response, fixing your example.

It is a bit funny that the numeric case still worked... Mosaic was (incorrectly) passing a nested array value to Plot in either case, and Plot apparently extracts the nested numerical value, but not the Date value.
