### ISSUE TITLE
panZoomX  scale.invert is not a function  barY

### ISSUE THREAD

**Issue by kzmKZuzmo** [uwdata/mosaic#518]
` 
        {

            "params": {
                "xs": {
                    "select": "intersect"
                }
            },

            "plot": [
                {
                    "legend": "color", "as": "$click", "columns": 3
                },
                {
                    "mark": "barY",
                    "data": { "from": "tableData", "filterBy": "$range" },
                    "x": "CatName",
                    "y": { "count": "Pid" },
                    "fill": "CatGroup"
                },
                {
                    "select": "panZoomX",
                    "x": "$xs"
                },

            ],
            "width": 680,
            "height": 240,

        }`
        
 
         
![image](https://github.com/user-attachments/assets/7ff85a4a-4ebe-431d-b83d-7aded84c46c3)

    "@uwdata/vgplot": "^0.10.0",      
        

![image](https://github.com/user-attachments/assets/434af0c4-ccb5-49cc-8274-3a07a1dde378)
when I stringify  slace object result is this also with data.
{
	"type": "band",
"domain": [.....],
	"range": [
		40,
		660
	],
	"align": 0.5,
	"round": false,
	"paddingInner": 0.1,
	"paddingOuter": 0.1,
	"bandwidth": 2.276621787025704,
	"step": 2.5295797633618933
}

**Comment by jheer** [comment]
Yes, unfortunately ordinal scales (as implemented in Plot and D3) do not support inversion akin to continuous scales. As a result, the interval selections are only well defined for continuous data domains. If you have a discrete (ordinal) domain, you can use a toggle selector instead to select discrete elements.
