### ISSUE TITLE
stacked area chart: inconsistent order

### ISSUE THREAD

**Issue by declann** [uwdata/mosaic#525]
I get the following effect using `vgplot.rectY` and a fill channel for a stacked area chart.

~~~js
vg.rectY(vg.from("base"),
{
  x: 'month',
  y: vg.sum('value'),
  fill: 'cashflow'
})
~~~

![image](https://github.com/user-attachments/assets/daa3fdf8-3035-4649-85c4-43ae3e11566d)

The colors aren't displayed in a consistent order (bottom).

I was confused because I moved to a Vega client, and I got the same bug in the **exact same positions** - but this helped me understand that I needed an orderby clause in my query (something to do with duckdb), so my Vega client is now fixed.

Should vgplot include an orderby clause for consistent ordering by default, when using a stack transform? (I might be missing a simple way to add this: will update if I find it)

**Comment by jheer** [comment]
I've also struggled with this in the past, part of the issue is getting the underlying Plot library to do what we want. Have you tried something like the following? IIRC, a confusing part was needing to give Plot a `z` channel in addition to `fill`.

```js
vg.rectY(vg.from('base'), {
  x: 'month',
  y: vg.sum('value'),
  fill: 'cashflow',
  z: 'cashflow',
  order: 'z'
})
```

The `order` channel here is actually an option passed to [Plot's stack transform](https://observablehq.com/plot/transforms/stack#stack-options). Instead of specifying the `z` channel, another alternative could be to provide an explicit array of ordered domain values to `order`.

**Comment by declann** [comment]
Thanks for the suggestion Jeff!

> ```js
> vg.rectY(vg.from('base'), {
>   x: 'month',
>   y: vg.sum('value'),
>   fill: 'cashflow',
>   z: 'cashflow',
>   order: 'z'
> })
> ```

This does work!

## vega lite

![image](https://github.com/user-attachments/assets/af6e0430-e43d-47f1-a70a-0de660b035e3)

To explain this I now notice that **in my Vega Lite spec I was using a bad `order` field**.

This means order was the issue in both cases. d3 stack probably needs a deliberate [orderby](https://d3js.org/d3-shape/stack#stack_order) or it won't cope robustly with out-of-order data (speculating a little).

In Vega Lite, it's actually hard to encounter this (except for my error). Even without specifying order it will generate 

~~~js
        {
          "type": "stack",
          "groupby": ["month"],
          "field": "value",
          "sort": {
            "field": ["cashflow"], // will also capture other mapped fields, e.g. to detail channel
            "order": ["descending"]
          },
          "as": ["value_start", "value_end"],
          "offset": "zero"
        }
~~~

Not sure if replicating Vega Lites intuitive behavior is something Mosaic should also do. `z` channel and `order` trick works - whenever the problem is understood!

Thanks for the fix!
