### ISSUE TITLE
LoadCSV with URL not working with Proxy Passing

### ISSUE THREAD

**Issue by bbollen23** [uwdata/mosaic#526]
Hi there,

We're having an issue accessing served files using load CSV when passing through nginx.

We have an NGINX server that proxy passes requests from "http://localhost/data" to "http://data:9000" within a docker container. When calling

```js
await vg.coordinator().exec([vg.loadCSV(tableName, "http://localhost/data/my_file.csv")]);
```
it will give an IO error in the console:

Uncaught (in promise) Error: IO Error: Connection error for HTTP HEAD to 'http://localhost/data/my_file.csv'

However, if we instead change this to the actual Docker network url to this,

```js
await vg.coordinator().exec([vg.loadCSV(tableName, "http://data:9000/data/my_file.csv")]);
```
then it will work. We've verified that NGINX is properly configured and that "http://localhost/data" properly proxy passes to the data server. We have to load in the data in other ways aside from mosaic and they all work (e.g. `fetch("http://localhost/data/my_file.csv")` works successfully).

I've looked into the Github repo and can't see any malforming of the URL or anything else, so I was wondering if there is just some inherent issue with the loading functions that prevent us from accessing it using proxy passing. Our biggest issue is that our dev environment usually has a separate client which doesn't have access to the data server directly (via 'http://data:9000') but is able to access it through NGINX. 

Any info would be greatly appreciated.

Best,
Brian

**Comment by jheer** [comment]
Thanks for sharing the issue. All that `vg.loadCSV` does is create a DuckDB query that loads a table from a CSV file -- you can log the output of the method to see the result. So whatever isn't working here is most likely a DuckDB issue, or an intentional feature limitation. Based on your description I suspect the issue concerns DuckDB's [httpfs extension](https://duckdb.org/docs/extensions/httpfs/overview). I recommend filing an issue / seeking support with the DuckDB team. Sorry I can't be more helpful than that!

**Comment by bbollen23** [comment]
Thank you for all the info! But yes, looking at the Github code, it didn't seem like Mosaic was doing anything extra when loading the CSV so I did try and dig into duckdb a bit beforehand to no avail. I'll take a look and see if others are having the same issues. I appreciate the clarity, though, that it is a DuckDB issue, not a Mosaic issue.

Thanks again!

**Comment by jheer** [comment]
Glad you found a solution. Thanks for sharing!
