### ISSUE TITLE
Running duckdb-server-rust panics

### ISSUE THREAD

**Issue by simonkaltenbacher** [uwdata/mosaic#548]
Trying to run the Rust version of duckdb-server results in the following error message:

```
thread 'main' panicked at /home/simon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/duckdb-server-0.1.0/src/main.rs:100:6:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: duckdb_server::main::{{closure}}
   4: tokio::runtime::runtime::Runtime::block_on
   5: duckdb_server::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by domoritz** [comment]
Do you see this with the released version from cargo or the dev version in this repo? Can you try to repro it in the other?

**Comment by domoritz** [comment]
Oh, I think I fixed this. It's because it wants the certificates. I need to make a new release. Working on it.

**Comment by domoritz** [comment]
Try 0.1.1. You won't get https or http/2 without a certificate as described in the readme but at least the server works with ws and http/1 now without crashing.

**Comment by simonkaltenbacher** [comment]
Thanks a lot for the immediate response and the fix. With local certificates version 0.1 was also not working for me. However, the new version solved all issues. Now it works flawlessly with and without local certificates.
