### ISSUE TITLE
Return dataServer to allow for closing

### ISSUE THREAD

**Issue by mhkeller** [uwdata/mosaic#553]
In a simple example running the node duckdb data server, I didn't see a way to close the server since the `dataServer` function doesn't return. I think you would need `return app.listen(port)` [here](https://github.com/uwdata/mosaic/blob/bce92a7e6a92c71859357542b7da656646d97113/packages/duckdb/src/data-server.js#L22).

Happy to start a PR with this if useful and I'm not missing something simple that would allow me to run `app.close()` after instantiating the server.

edit: that `return` example above was just illustrative. In practice, you would want the return to follow the logs, obviously

```js
const server = app.listen(port);
console.log(`Data server running on port ${port}`);
if (rest) console.log(`  http://localhost:${port}/`);
if (socket) console.log(`  ws://localhost:${port}/`);
return server;
```

**Comment by jheer** [comment]
Thanks! A PR adding this change would be much appreciated.

**Comment by domoritz** [comment]
Done in #554
