### ISSUE TITLE
Cannot load FileAttachment into Observable notebook via data loaders

### ISSUE THREAD

**Issue by josesho** [uwdata/mosaic#581]
All the examples on the Mosaic site load data from URLs or a local file (presumably for use in a Framework project).

However, there are no working examples for loading a `FileAttachment` as data, and I can't seem to get it to work either `loadCSV()`, `loadParquet()`, or `loadObjects()`

Exemplar notebook here: https://observablehq.com/@josesho/mosaic-troubleshoot-loading-data

Any help here is appreciated!

**Comment by domoritz** [comment]
Moved to https://github.com/uwdata/mosaic/discussions/582
