### ISSUE TITLE
dark mode example

### ISSUE THREAD

**Issue by Fil** [uwdata/mosaic#600]
the multi-line chart at https://idl.uw.edu/mosaic/examples/region-tests.html is no visible in dark mode; it should probably use a different set of colors, and a different mixBlendMode.
<img width="665" alt="Capture d’écran 2024-11-22 à 08 01 56" src="https://github.com/user-attachments/assets/539256d0-bef3-49c1-9db3-4f5bd2b20c41">

**Comment by jheer** [comment]
Thanks for catching this! The issue seems to be hold on both Chrome and Safari. We missed this earlier as Firefox still renders things in a visible manner.
