### ISSUE TITLE
widget: version `0.12.2` not published to PyPi

### ISSUE THREAD

**Issue by declann** [uwdata/mosaic#630]
Hi,

Latest update on PyPi is `0.12.0`:

https://pypi.org/project/mosaic-widget/#history

**Comment by domoritz** [comment]
Uploaded just now.

**Comment by domoritz** [comment]
Hmm, I guess I didn't rebuild explicitly. We should look into a setup that automatically deploys rather than error prone manual deploys.

**Comment by domoritz** [comment]
I'll make another release in a bit.

**Comment by jheer** [comment]
> Hmm, I guess I didn't rebuild explicitly. We should look into a setup that automatically deploys rather than error prone manual deploys.

We do have automatic Python lib deploys in place through the `npm run release` (which in turn calls `npm run release:python`, which in turn calls `npm run release:server` and  `npm run release:widget`). But based on this issue it seems these are buggy, so it would be wonderful to get them fixed.

**Comment by domoritz** [comment]
Ah, I didn't know you wanted to run python publish from the npm scripts since it requires additional setup of the python tooling. I originally didn't add it but now that we have uv it should be easier so I can update the commands.

**Comment by domoritz** [comment]
Done in https://github.com/uwdata/mosaic/pull/632
